# Generated by Django 2.0.6 on 2018-06-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
